// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	compute "picodb/internal/database/compute"

	mock "github.com/stretchr/testify/mock"
)

// QueryAnalyzer is an autogenerated mock type for the QueryAnalyzer type
type QueryAnalyzer struct {
	mock.Mock
}

// AnalyzeQuery provides a mock function with given fields: _a0, _a1
func (_m *QueryAnalyzer) AnalyzeQuery(_a0 context.Context, _a1 []string) (compute.Query, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeQuery")
	}

	var r0 compute.Query
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (compute.Query, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) compute.Query); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(compute.Query)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQueryAnalyzer creates a new instance of QueryAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryAnalyzer {
	mock := &QueryAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
