name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v5.0.0
      with:
        go-version: 1.21

    - uses: nickhstr/action-setup-golangci-lint@v0.1.0
      with:
        version: 1.54.2

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test
  
